spring:
  application:
    name: main-service
  config:
    import: "optional:configserver:${CONFIG_URI:http://localhost:8888}"
  cloud:
    config:
      fail-fast: true     # Если конфиг не получен — падать сразу (чтобы видеть ошибку)
      retry:
        initial-interval: 1000  # Пробовать снова через 1 секунду
        max-interval: 2000      # Максимум ждать 2 секунды
        max-attempts: 6         # Пробовать 6 раз