global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'main-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['main-service:8081']
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8080']